#$Id$
%.test: %.py
	@echo ===============
	#PYTHONPATH=../../..:..
	python $*.py -v

#znow: test_inh_types.test

now: concrete.test
now: inherit.test
now: inherit2.test
now: single.test

# vim:ts=4:sw=4:noexpandtab
